FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

# Copy scripts for subprocess calls
COPY ./analytics /app/analytics
COPY ./load /app/load

CMD ["python", "app.py"]
